/*
 * DO NOT EDIT.  THIS FILE IS GENERATED FROM nsINavHistoryService.idl
 */

module mozilla.xpcom.nsINavHistoryService;


public import mozilla.xpcom.nsrootidl;

public import mozilla.xpcom.nsISupports;
public import mozilla.xpcom.nsIArray;
public import mozilla.xpcom.nsIURI;

public import mozilla.xpcom.nsIFile; /* forward declaration */

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsINavHistoryService;

public import mozilla.xpcom.nsITreeColumns;

public import mozilla.xpcom.nsIWritablePropertyBag; /* forward declaration */


/* starting interface:    nsINavHistoryResultNode */
const char[] NS_INAVHISTORYRESULTNODE_IID_STR = "acae2b2d-5fcd-4419-b1bc-b7dc92a1836c";

const nsIID NS_INAVHISTORYRESULTNODE_IID= 
  {0xacae2b2d, 0x5fcd, 0x4419, 
    [ 0xb1, 0xbc, 0xb7, 0xdc, 0x92, 0xa1, 0x83, 0x6c ]};

extern(Windows)
interface nsINavHistoryResultNode : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYRESULTNODE_IID;

  /**
   * Indentifies the parent result node in the result set. This is null for
   * top level nodes.
   */
  /* readonly attribute nsINavHistoryContainerResultNode parent; */
  nsresult GetParent(nsINavHistoryContainerResultNode  *aParent);

  /**
   * URI of the resource in question. For visits and URLs, this is the URL of
   * the page. For folders and queries, this is the place: URI of the
   * corresponding folder or query. This may be empty for other types of
   * objects like host containers.
   */
  /* readonly attribute AUTF8String uri; */
  nsresult GetUri(nsACString * aUri);

  /**
   * Identifies the type of this node. This node can then be QI-ed to the
   * corresponding specialized result node interface. The remote_container one
   * is a little weird, it is a temportary folder generated by the remote
   * container API. Note that bookmark folders can also be filled by the
   * remote container API (these are the entrypoints for the API) and may
   * have a remote container type as well.
   */
  enum { RESULT_TYPE_URI = 0U };

  enum { RESULT_TYPE_VISIT = 1U };

  enum { RESULT_TYPE_FULL_VISIT = 2U };

  enum { RESULT_TYPE_HOST = 3U };

  enum { RESULT_TYPE_REMOTE_CONTAINER = 4U };

  enum { RESULT_TYPE_QUERY = 5U };

  enum { RESULT_TYPE_FOLDER = 6U };

  enum { RESULT_TYPE_SEPARATOR = 7U };

  /* readonly attribute PRUint32 type; */
  nsresult GetType(PRUint32 *aType);

  /**
   * Title of the web page, or of the node's grouping (day, host, folder, etc)
   */
  /* readonly attribute AUTF8String title; */
  nsresult GetTitle(nsACString * aTitle);

  /**
   * Total number of times the URI has ever been accessed. For hosts, this
   * is the total of the children under it, NOT the total times the host has
   * been accessed (this would require an additional query, so is not given
   * by default when most of the time it is never needed).
   */
  /* readonly attribute PRUint32 accessCount; */
  nsresult GetAccessCount(PRUint32 *aAccessCount);

  /**
   * This is the time the user accessed the page.
   *
   * If this is a visit, it is the exact time that the page visit occurred.
   *
   * If this is a URI, it is the most recent time that the URI was visited.
   * Even if you ask for all URIs for a given date range long ago, this might
   * contain today's date if the URI was visited today.
   *
   * For hosts, or other node types with children, this is the most recent
   * access time for any of the children.
   *
   * For days, this is midnight on the morning of the day in question in
   * UTC time.
   */
  /* readonly attribute PRTime time; */
  nsresult GetTime(PRTime *aTime);

  /**
   * This URI can be used as an image source URI and will give you the favicon
   * for the page. It is *not* the URI of the favicon, but rather something
   * that will resolve to the actual image.
   *
   * In most cases, this is an annotation URI that will query the favicon
   * service. If the entry has no favicon, this is the chrome URI of the
   * default favicon. If the favicon originally lived in chrome, this will
   * be the original chrome URI of the icon.
   */
  /* readonly attribute nsIURI icon; */
  nsresult GetIcon(nsIURI  *aIcon);

  /**
   * This is the number of levels between this node and the top of the
   * hierarchy. The members of result.children have indentLevel = 0, their
   * children have indentLevel = 1, etc.
   */
  /* readonly attribute PRUint32 indentLevel; */
  nsresult GetIndentLevel(PRUint32 *aIndentLevel);

  /**
   * Value with undefined meaning for use by the view. Its initial value will
   * be -1. The tree view uses this value to indicate the row in the tree that
   * this node is at. Other views may use this value however they choose.
   */
  /* attribute PRInt32 viewIndex; */
  nsresult GetViewIndex(PRInt32 *aViewIndex);
  nsresult SetViewIndex(PRInt32 aViewIndex);

  /**
   * You can use this to associate temporary information with the result node.
   * This property bag is associated with the result node and is not persisted
   * in any way.
   */
  /* readonly attribute nsIWritablePropertyBag propertyBag; */
  nsresult GetPropertyBag(nsIWritablePropertyBag  *aPropertyBag);

  /**
   * When this item is in a bookmark folder (parent is of type folder), this is
   * the index into that folder of this node. These indices start at 0 and
   * increase in the order that they appear in the bookmark folder. For items
   * that are not in a bookmark folder, this value is -1.
   */
  /* readonly attribute PRInt32 bookmarkIndex; */
  nsresult GetBookmarkIndex(PRInt32 *aBookmarkIndex);

}


/* starting interface:    nsINavHistoryVisitResultNode */
const char[] NS_INAVHISTORYVISITRESULTNODE_IID_STR = "8e2c5a86-b33d-4fa6-944b-559af7e95fcd";

const nsIID NS_INAVHISTORYVISITRESULTNODE_IID= 
  {0x8e2c5a86, 0xb33d, 0x4fa6, 
    [ 0x94, 0x4b, 0x55, 0x9a, 0xf7, 0xe9, 0x5f, 0xcd ]};

/**
 * When you request RESULT_TYPE_VISIT from query options, you will get this
 * interface for each item, which includes the session ID so that we can
 * group items from the same session together.
 */
extern(Windows)
interface nsINavHistoryVisitResultNode : nsINavHistoryResultNode {
  static const char[] IID_STR = NS_INAVHISTORYVISITRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYVISITRESULTNODE_IID;

  /**
   * This indicates the session ID of the * visit. This is used for session
   * grouping when a tree view is sorted by date.
   */
  /* readonly attribute PRInt64 sessionId; */
  nsresult GetSessionId(PRInt64 *aSessionId);

}


/* starting interface:    nsINavHistoryFullVisitResultNode */
const char[] NS_INAVHISTORYFULLVISITRESULTNODE_IID_STR = "c49fd9d5-56e2-43eb-932c-f933f28cba85";

const nsIID NS_INAVHISTORYFULLVISITRESULTNODE_IID= 
  {0xc49fd9d5, 0x56e2, 0x43eb, 
    [ 0x93, 0x2c, 0xf9, 0x33, 0xf2, 0x8c, 0xba, 0x85 ]};

/**
 * This structure will be returned when you request RESULT_TYPE_FULL_VISIT in
 * the query options. This includes uncommonly used information about each
 * visit.
 */
extern(Windows)
interface nsINavHistoryFullVisitResultNode : nsINavHistoryVisitResultNode {
  static const char[] IID_STR = NS_INAVHISTORYFULLVISITRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYFULLVISITRESULTNODE_IID;

  /**
   * This indicates the visit ID of the visit.
   */
  /* readonly attribute PRInt64 visitId; */
  nsresult GetVisitId(PRInt64 *aVisitId);

  /**
   * This indicates the referring visit ID of the visit. The referrer should
   * have the same sessionId.
   */
  /* readonly attribute PRInt64 referringVisitId; */
  nsresult GetReferringVisitId(PRInt64 *aReferringVisitId);

  /**
   * Indicates the transition type of the visit.
   * One of nsINavHistoryService.TRANSITION_*
   */
  /* readonly attribute PRInt32 transitionType; */
  nsresult GetTransitionType(PRInt32 *aTransitionType);

}


/* starting interface:    nsINavHistoryContainerResultNode */
const char[] NS_INAVHISTORYCONTAINERRESULTNODE_IID_STR = "957065fd-76e7-4c24-9284-c31b5decbaaa";

const nsIID NS_INAVHISTORYCONTAINERRESULTNODE_IID= 
  {0x957065fd, 0x76e7, 0x4c24, 
    [ 0x92, 0x84, 0xc3, 0x1b, 0x5d, 0xec, 0xba, 0xaa ]};

extern(Windows)
interface nsINavHistoryContainerResultNode : nsINavHistoryResultNode {
  static const char[] IID_STR = NS_INAVHISTORYCONTAINERRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYCONTAINERRESULTNODE_IID;

  /**
 * Base class for container results. This includes all types of groupings.
 * Bookmark folders and places queries will be QueryResultNodes which extends
 * these items.
 */
/**
   * Set this to allow descent into the container. When closed, attempting
   * to call getChildren or childCount will result in an error. You should
   * set this to false when you are done reading.
   *
   * For HOST and DAY groupings, doing this is free since the children have
   * been precomputed. For queries and bookmark folders, being open means they
   * will keep themselves up-to-date by listening for updates and re-querying
   * as needed.
   */
  /* attribute boolean containerOpen; */
  nsresult GetContainerOpen(PRBool *aContainerOpen);
  nsresult SetContainerOpen(PRBool aContainerOpen);

  /**
   * This indicates whether this node "may" have children, and can be used
   * when the container is open or closed. When the container is closed, it
   * will give you an exact answer if the node can easily be populated (for
   * example, a bookmark folder). If not (for example, a complex history query),
   * it will return true. When the container is open, it will always be
   * accurate. It is intended to be used to see if we should draw the "+" next
   * to a tree item.
   */
  /* readonly attribute boolean hasChildren; */
  nsresult GetHasChildren(PRBool *aHasChildren);

  /**
   * This gives you the children of the nodes. It is preferrable to use this
   * interface over the array one, since it avoids creating an nsIArray object
   * and the interface is already the correct type.
   */
  /* readonly attribute PRUint32 childCount; */
  nsresult GetChildCount(PRUint32 *aChildCount);

  /* nsINavHistoryResultNode getChild (in PRUint32 index); */
  nsresult GetChild(PRUint32 index, nsINavHistoryResultNode *_retval);

  /**
   * Returns false if this node's list of children can be modified
   * (adding or removing children, or reordering children), or true if
   * the UI should not allow the list of children to be modified.
   * This is false for bookmark folder nodes unless setFolderReadOnly() has
   * been called to override it, and true for non-folder nodes. If this
   * container is a remote container this flag may be redefined by the
   * remote container provider.
   */
  /* readonly attribute boolean childrenReadOnly; */
  nsresult GetChildrenReadOnly(PRBool *aChildrenReadOnly);

  /**
   * This is a string representing the remote container API service that is
   * responsible for this container. It is empty if there is none.  The 
   * container may be a RESULT_TYPE_REMOTE_CONTAINER node that has been 
   * dynamically generated by the remote container API.  It may also be a 
   * bookmark folder (RESULT_TYPE_FOLDER) for which some service (such as 
   * livemarks) has registered to provide certain operations.
   */
  /* readonly attribute AUTF8String remoteContainerType; */
  nsresult GetRemoteContainerType(nsACString * aRemoteContainerType);

}


/* starting interface:    nsINavHistoryQueryResultNode */
const char[] NS_INAVHISTORYQUERYRESULTNODE_IID_STR = "dcd6a2b7-3d50-4c78-b1cb-2f0f18ac5864";

const nsIID NS_INAVHISTORYQUERYRESULTNODE_IID= 
  {0xdcd6a2b7, 0x3d50, 0x4c78, 
    [ 0xb1, 0xcb, 0x2f, 0x0f, 0x18, 0xac, 0x58, 0x64 ]};

extern(Windows)
interface nsINavHistoryQueryResultNode : nsINavHistoryContainerResultNode {
  static const char[] IID_STR = NS_INAVHISTORYQUERYRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYQUERYRESULTNODE_IID;

  /**
   * Appends a full visit node to this container and returns it. For the remote
   * container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * @see nsINavHistoryURIResultNode for parameters.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Appends a full visit node to this container and returns it. For the remote
   * container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * @see nsINavHistoryVisitResultNode for parameters.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Appends a full visit node to this container and returns it. For the remote
   * container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * @see nsINavHistoryFullVisitResultNode for parameters.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Appends a container node to this container and returns it. For the remote
   * container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * aContainerType should be either RESULT_TYPE_HOST or
   * RESULT_TYPE_REMOTE_CONTAINER. When type is remote container you must
   * specify a remote container type, otherwise, the remote container type must
   * be null. Use appendQueryNode and appendFolderNode for the other container
   * types.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Appends a query node to this container and returns it. For the remote
   * container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * Normally you should supply an empty string for IconURI and it will take
   * the default query icon for the current theme.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Appends a bookmark folder node to this container and returns it. For the
   * remote container API. TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening()
   * ONLY, and only for non-bookmark-folder containers.
   *
   * All container attributes will come from the boomkarks service for this
   * folder.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
   * Clears all children of this container. For the remote container API.
   * TO BE CALLED FROM nsIRemoteContainer::OnContainerOpening and
   * nsIRemoteContainer::OnContainerClosed ONLY, and valid only for
   * non-bookmark-folder containers.
   *
   * UNTESTED: Container API functions are commented out until we can test
   */
/**
 * Used for places queries and as a base for bookmark folders.
 *
 * Note that if you request places to *not* be expanded in the options that
 * generated this node, this item will report it has no children and never try
 * to populate itself.
 */
/**
   * Get the queries which build this node's children.
   * Only valid for RESULT_TYPE_QUERY nodes.
   */
  /* void getQueries (out unsigned long queryCount, [array, size_is (queryCount), retval] out nsINavHistoryQuery queries); */
  nsresult GetQueries(PRUint32 *queryCount, nsINavHistoryQuery **queries);

  /**
   * Get the options which group this node's children.
   * Only valid for RESULT_TYPE_QUERY nodes.
   */
  /* readonly attribute nsINavHistoryQueryOptions queryOptions; */
  nsresult GetQueryOptions(nsINavHistoryQueryOptions  *aQueryOptions);

}


/* starting interface:    nsINavHistoryFolderResultNode */
const char[] NS_INAVHISTORYFOLDERRESULTNODE_IID_STR = "f3160bfe-ebb3-453b-b25e-19d0b9c425b1";

const nsIID NS_INAVHISTORYFOLDERRESULTNODE_IID= 
  {0xf3160bfe, 0xebb3, 0x453b, 
    [ 0xb2, 0x5e, 0x19, 0xd0, 0xb9, 0xc4, 0x25, 0xb1 ]};

extern(Windows)
interface nsINavHistoryFolderResultNode : nsINavHistoryQueryResultNode {
  static const char[] IID_STR = NS_INAVHISTORYFOLDERRESULTNODE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYFOLDERRESULTNODE_IID;

  /**
 * Represents a bookmark folder (type == RESULT_TYPE_FOLDER). It derives from a
 * query result because it can provide a query that will result in the
 * contents.
 */
/**
   * ID of the folder corresponding to this node.
   * Only valid for RESULT_TYPE_QUERY nodes where exactly one folder
   * has been specified in the query.  0 in all other cases.
   */
  /* readonly attribute PRInt64 folderId; */
  nsresult GetFolderId(PRInt64 *aFolderId);

}


/* starting interface:    nsINavHistoryResultViewObserver */
const char[] NS_INAVHISTORYRESULTVIEWOBSERVER_IID_STR = "b34d5ca4-ce8e-49a6-9201-a59ae2128d2c";

const nsIID NS_INAVHISTORYRESULTVIEWOBSERVER_IID= 
  {0xb34d5ca4, 0xce8e, 0x49a6, 
    [ 0x92, 0x01, 0xa5, 0x9a, 0xe2, 0x12, 0x8d, 0x2c ]};

/**
 *  Allows clients of the HistoryResult to define domain specific handling 
 *  of specific nsITreeView methods that the HistoryResult does not implement.
 *
 *  @see nsINavHistoryResult for where this fits in
 */
extern(Windows)
interface nsINavHistoryResultViewObserver : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYRESULTVIEWOBSERVER_IID_STR;
  static const nsIID IID = NS_INAVHISTORYRESULTVIEWOBSERVER_IID;

  enum { DROP_BEFORE = -1 };

  enum { DROP_ON = 0 };

  enum { DROP_AFTER = 1 };

  /**
   * Methods used by the drag feedback code to determine if a drag is allowable at
   * the current location. To get the behavior where drops are only allowed on
   * items, such as the mailNews folder pane, always return false whe
   * the orientation is not DROP_ON. Implementors should not change the content of
   * the observer list!
   */
  /* boolean canDrop (in long index, in long orientation); */
  nsresult CanDrop(PRInt32 index, PRInt32 orientation, PRBool *_retval);

  /**
   * Called when the user drops something on this view. The |orientation| param
   * specifies before/on/after the given |row|.
   */
  /* void onDrop (in long row, in long orientation); */
  nsresult OnDrop(PRInt32 row, PRInt32 orientation);

  /** 
   * Called when an item is opened or closed. 
   */
  /* void onToggleOpenState (in long index); */
  nsresult OnToggleOpenState(PRInt32 index);

  /** 
 * Called when a header is clicked.
   */
  /* void onCycleHeader (in nsITreeColumn column); */
  nsresult OnCycleHeader(nsITreeColumn column);

  /**
   * Called when a cell in a non-selectable cycling column (e.g. 
   * unread/flag/etc.) is clicked.
   */
  /* void onCycleCell (in long row, in nsITreeColumn column); */
  nsresult OnCycleCell(PRInt32 row, nsITreeColumn column);

  /** 
   * Called when selection in the tree changes
   */
  /* void onSelectionChanged (); */
  nsresult OnSelectionChanged();

  /**
   * A command API that can be used to invoke commands on the selection.  
   * The tree will automatically invoke this method when certain keys 
   * are pressed.  For example, when the DEL key is pressed, performAction 
   * will be called with the "delete" string. 
   */
  /* void onPerformAction (in wstring action); */
  nsresult OnPerformAction(PRUnichar *action);

  /**
   * A command API that can be used to invoke commands on a specific row.
   */
  /* void onPerformActionOnRow (in wstring action, in long row); */
  nsresult OnPerformActionOnRow(PRUnichar *action, PRInt32 row);

  /**
   * A command API that can be used to invoke commands on a specific cell.
   */
  /* void onPerformActionOnCell (in wstring action, in long row, in nsITreeColumn column); */
  nsresult OnPerformActionOnCell(PRUnichar *action, PRInt32 row, nsITreeColumn column);

}


/* starting interface:    nsINavHistoryResultViewer */
const char[] NS_INAVHISTORYRESULTVIEWER_IID_STR = "11032c23-a9fd-4918-bc8f-004726a748da";

const nsIID NS_INAVHISTORYRESULTVIEWER_IID= 
  {0x11032c23, 0xa9fd, 0x4918, 
    [ 0xbc, 0x8f, 0x00, 0x47, 0x26, 0xa7, 0x48, 0xda ]};

/**
 * Allows clients to observe what is happening to a result as it updates itself
 * according to history and bookmark system events. Register this observer on a
 * result using registerView
 *
 * @see nsINavHistoryResult for where this fits in
 */
extern(Windows)
interface nsINavHistoryResultViewer : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYRESULTVIEWER_IID_STR;
  static const nsIID IID = NS_INAVHISTORYRESULTVIEWER_IID;

  /**
   * Called when 'item' is inserted into 'parent' at index 'newIndex'. The item
   * previously at index (if any) and everything below it will have been
   * shifted down by one. The item may be a container or a leaf.
   */
  /* void itemInserted (in nsINavHistoryContainerResultNode parent, in nsINavHistoryResultNode item, in PRUint32 newIndex); */
  nsresult ItemInserted(nsINavHistoryContainerResultNode parent, nsINavHistoryResultNode item, PRUint32 newIndex);

  /**
   * Called whan 'item' is removed from 'parent' at 'oldIndex'. The item may be
   * a container or a leaf. This function will be called after the item has
   * been removed from its parent list, but before anything else (including
   * NULLing out the item's parent) has happened.
   */
  /* void itemRemoved (in nsINavHistoryContainerResultNode parent, in nsINavHistoryResultNode item, in PRUint32 oldIndex); */
  nsresult ItemRemoved(nsINavHistoryContainerResultNode parent, nsINavHistoryResultNode item, PRUint32 oldIndex);

  /**
   * Called when an item has been changed and should be repainted. This only
   * refers to the specific item. If it is a container, getting this message
   * does not imply anything happened to the children. You'll get separate
   * messages for those. Also, this may be called for container nodes at times
   * when the result thinks it's possible that a twisty mey need to bw redrawn.
   */
  /* void itemChanged (in nsINavHistoryResultNode item); */
  nsresult ItemChanged(nsINavHistoryResultNode item);

  /**
   * Called when an item is being replaced with another item at the exact
   * same position.
   */
  /* void itemReplaced (in nsINavHistoryContainerResultNode parent, in nsINavHistoryResultNode oldItem, in nsINavHistoryResultNode newItem, in PRUint32 index); */
  nsresult ItemReplaced(nsINavHistoryContainerResultNode parent, nsINavHistoryResultNode oldItem, nsINavHistoryResultNode newItem, PRUint32 index);

  /**
   * Called after a container node went from closed to opened.
   */
  /* void containerOpened (in nsINavHistoryContainerResultNode item); */
  nsresult ContainerOpened(nsINavHistoryContainerResultNode item);

  /**
   * Called after a container node went from opened to closed. This will be
   * called for the topmost container that is closing, and implies that any
   * child containers have closed as well.
   */
  /* void containerClosed (in nsINavHistoryContainerResultNode item); */
  nsresult ContainerClosed(nsINavHistoryContainerResultNode item);

  /**
   * Called when something significant has happened within the container. The
   * contents of the container should be re-built.
   */
  /* void invalidateContainer (in nsINavHistoryContainerResultNode item); */
  nsresult InvalidateContainer(nsINavHistoryContainerResultNode item);

  /**
   * Called when something significant is changing that requires everything
   * to be recomputed. For example, changing sorting or changing collapse
   * duplicates can affect every row.
   */
  /* void invalidateAll (); */
  nsresult InvalidateAll();

  /**
   * This is called to indicate to the UI that the sort has changed to the
   * given mode. For trees, for example, this would update the column headers
   * to reflect the sorting. For many other types of views, this won't be
   * applicable.
   *
   * @param sortingMode  One of nsINavHistoryQueryOptions.SORT_BY_* that
   *                     indicates the new sorting mode.
   *
   * This only is expected to update the sorting UI. invalidateAll() will also
   * get called if the sorting changes to update everything.
   */
  /* void sortingChanged (in PRUint32 sortingMode); */
  nsresult SortingChanged(PRUint32 sortingMode);

  /**
   * Called by the result when this object is set using
   * nsINavHistoryResult.viewer. This will be set to NULL when the result
   * is being deallocated. This should not be set by other code.
   */
  /* attribute nsINavHistoryResult result; */
  nsresult GetResult(nsINavHistoryResult  *aResult);
  nsresult SetResult(nsINavHistoryResult  aResult);

  /**
   * Adds the specified view observer to the view. In ownsWeak is false, then
   * the result will hold a strong reference to the observer. If ownsWeak is
   * true, then the observer must implement nsISupportsWeakReference, and the
   * result will hold a weak reference to the observer.
   */
  /* void addViewObserver (in nsINavHistoryResultViewObserver observer, in boolean ownsWeak); */
  nsresult AddViewObserver(nsINavHistoryResultViewObserver observer, PRBool ownsWeak);

  /**
   * Removes the specified view observer from this view. This observer must
   * have been previously registered using addViewObserver.
   */
  /* void removeViewObserver (in nsINavHistoryResultViewObserver observer); */
  nsresult RemoveViewObserver(nsINavHistoryResultViewObserver observer);

}


/* starting interface:    nsINavHistoryResultTreeViewer */
const char[] NS_INAVHISTORYRESULTTREEVIEWER_IID_STR = "ecd6ad22-8eb0-4824-8a57-5edad9a08ae6";

const nsIID NS_INAVHISTORYRESULTTREEVIEWER_IID= 
  {0xecd6ad22, 0x8eb0, 0x4824, 
    [ 0x8a, 0x57, 0x5e, 0xda, 0xd9, 0xa0, 0x8a, 0xe6 ]};

/**
 * A predefined view adaptor for interfacing results with an nsITree. This
 * object will remove itself from its associated result when the tree has been
 * detached. This prevents circular references. Users should be aware of this,
 * if you want to re-use the same viewer, you will need to keep your own
 * reference to it and re-initialize it when the tree changes. If you use this
 * object, attach it to a result, never attach it to a tree, and forget about
 * it, it will leak!
 */
extern(Windows)
interface nsINavHistoryResultTreeViewer : nsINavHistoryResultViewer {
  static const char[] IID_STR = NS_INAVHISTORYRESULTTREEVIEWER_IID_STR;
  static const nsIID IID = NS_INAVHISTORYRESULTTREEVIEWER_IID;

  /**
   * Controls whether duplicate adjacent elements are collapsed into a single
   * item in the tree. This prevents you from seeing multiple entries for
   * things when you have selected to get visits. When you sort by date, the
   * multiple entries will then appear because they will be separated (unless
   * you clicked reload a bunch of times in a row). If you know you'll only
   * ever want one entry per site, you should ask for URIs back instead of
   * visits so it will be more efficient.
   * Default = true
   *
   * Changing this value is somewhat heavyweight since it will force a tree
   * refresh.
   */
  /* attribute boolean collapseDuplicates; */
  nsresult GetCollapseDuplicates(PRBool *aCollapseDuplicates);
  nsresult SetCollapseDuplicates(PRBool aCollapseDuplicates);

  /**
   * This tells you how many items are in the flattened list of results, i.e.
   * how many rows are in this tree right now. The tree adaptor will also
   * QI to nsITreeView, and this will be the same as nsITreeView.rowCount.
   * This is only valid when a tree is attached, the result will be 0 otherwise.
   */
  /* readonly attribute PRUint32 flatItemCount; */
  nsresult GetFlatItemCount(PRUint32 *aFlatItemCount);

  /**
   * This allows you to get at the real node for a given row index. This is
   * only valid when a tree is attached.
   */
  /* nsINavHistoryResultNode nodeForTreeIndex (in PRUint32 aIndex); */
  nsresult NodeForTreeIndex(PRUint32 aIndex, nsINavHistoryResultNode *_retval);

  /**
   * Reverse of nodeForFlatIndex, returns the row index for a given result node.
   * Returns INDEX_INVISIBLE if the item is not visible (for example, its
   * parent is collapsed). This is only valid when a tree is attached. The
   * the result will always be INDEX_INVISIBLE if not.
   * 
   * Note: This sounds sort of obvious, but it got me: aNode must be a node
   *       retrieved from the same result that this viewer is for. If you 
   *       execute another query and get a node from a _different_ result, this 
   *       function will always return the index of that node in the tree that
   *       is attached to that result.
   */
  enum { INDEX_INVISIBLE = 4294967295U };

  /* PRUint32 treeIndexForNode (in nsINavHistoryResultNode aNode); */
  nsresult TreeIndexForNode(nsINavHistoryResultNode aNode, PRUint32 *_retval);

}


/* starting interface:    nsINavHistoryResult */
const char[] NS_INAVHISTORYRESULT_IID_STR = "25b45a94-3323-4c7b-910a-315f2c59bfb4";

const nsIID NS_INAVHISTORYRESULT_IID= 
  {0x25b45a94, 0x3323, 0x4c7b, 
    [ 0x91, 0x0a, 0x31, 0x5f, 0x2c, 0x59, 0xbf, 0xb4 ]};

extern(Windows)
interface nsINavHistoryResult : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYRESULT_IID_STR;
  static const nsIID IID = NS_INAVHISTORYRESULT_IID;

  /**
 * The result of a history/bookmark query.
 *
 * Use the "root" element to access the children of this query.
 *
 * The basic design of the system is a model-view-controller. This result object
 * represents the model where the data is stored. External components
 * provide the view and controller which define how the data looks and how
 * interaction happens.
 *                           +-- nsINavHistoryResultViewObserver
 *                           |
 *   [RESULT]----->[viewer]----->[controller]
 *             |
 *             +-- nsINavHistoryResultViewer
 *
 * The result indicates to the view when something changes through the
 * nsINavHistoryResultViewer interface. Viewers register themselves through
 * the nsINavHistoryResult.RegisterViewer. The viewer interface would then tell
 * the actual view object what to do. A nsINavHistoryResultTreeViewer is
 * provided which provides pre-packaged interaction with a nsITreeBoxObject.
 * Other views will need to provide their own viewer interfaces.
 *
 * The viewer provides notifications to the controller when view events occur
 * through the nsINavHistoryResultViewObserver interface.
 */
/**
   * Sorts all nodes recursively by the given parameter, one of
   * nsINavHistoryQueryOptions.SORT_BY_*  This will update the corresponding
   * options for this result, so that re-using the current options/queries will
   * always give you the current view.
   */
  /* attribute PRUint32 sortingMode; */
  nsresult GetSortingMode(PRUint32 *aSortingMode);
  nsresult SetSortingMode(PRUint32 aSortingMode);

  /**
   * The viewer for this result (see comment for the class for how these
   * objects are related). This may be null, in which case you can still
   * manually walk the tree using the root node. When this is non-null, you
   * can access the flattened list of items (flatItemCount, nodeForFlatIndex,
   * flatIndexForNode).
   */
  /* attribute nsINavHistoryResultViewer viewer; */
  nsresult GetViewer(nsINavHistoryResultViewer  *aViewer);
  nsresult SetViewer(nsINavHistoryResultViewer  aViewer);

  /**
   * This is the root of the results.  It will either be a
   * nsINavHistoryFolderResultNode (if the query is for bookmarks matching a
   * single folder) or just a nsINavHistoryQueryResultNode (for everything
   * else). Remember that you need to open all containers for their contents 
   * to be valid.
   */
  /* readonly attribute nsINavHistoryQueryResultNode root; */
  nsresult GetRoot(nsINavHistoryQueryResultNode  *aRoot);

}


/* starting interface:    nsINavHistoryObserver */
const char[] NS_INAVHISTORYOBSERVER_IID_STR = "849e2184-3dee-416f-91cd-6a619ca49d1c";

const nsIID NS_INAVHISTORYOBSERVER_IID= 
  {0x849e2184, 0x3dee, 0x416f, 
    [ 0x91, 0xcd, 0x6a, 0x61, 0x9c, 0xa4, 0x9d, 0x1c ]};

/**
 * Similar to nsIRDFObserver for history. Note that we don't pass the data
 * source since that is always the global history.
 *
 * DANGER! If you are in the middle of a batch transaction, there may be a
 * database transaction active. You can still access the DB, but be careful.
 */
extern(Windows)
interface nsINavHistoryObserver : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYOBSERVER_IID_STR;
  static const nsIID IID = NS_INAVHISTORYOBSERVER_IID;

  /**
   * Notifies you that a bunch of things are about to change, don't do any
   * heavy-duty processing until onEndUpdateBatch is called.
   */
  /* void onBeginUpdateBatch (); */
  nsresult OnBeginUpdateBatch();

  /**
   * Notifies you that we are done doing a bunch of things and you should go
   * ahead and update UI, etc.
   */
  /* void onEndUpdateBatch (); */
  nsresult OnEndUpdateBatch();

  /**
   * Called when a resource is visited. This is called the first time a
   * resource (page, image, etc.) is seen as well as every subsequent time.
   *
   * Normally, transition types of TRANSITION_EMBED (corresponding to images in
   * a page, for example) are not displayed in history results (unless
   * includeHidden is set). Many observers can ignore _EMBED notifications
   * (which will comprise the majority of visit notifications) to save work.
   *
   * @param aVisitID        ID of the visit that was just created.
   * @param aTime           Time of the visit
   * @param aSessionID      The ID of one connected sequence of visits.
   * @param aReferringID    The ID of the visit the user came from. 0 if empty.
   * @param aTransitionType One of nsINavHistory.TRANSITION_*
   */
  /* void onVisit (in nsIURI aURI, in PRInt64 aVisitID, in PRTime aTime, in PRInt64 aSessionID, in PRInt64 aReferringID, in PRUint32 aTransitionType); */
  nsresult OnVisit(nsIURI aURI, PRInt64 aVisitID, PRTime aTime, PRInt64 aSessionID, PRInt64 aReferringID, PRUint32 aTransitionType);

  /**
   * Called whenever either the "real" title or the custom title of the page
   * changed. BOTH TITLES ARE ALWAYS INCLUDED in this notification, even though
   * only one will change at a time. Often, consumers will want to display the
   * user title if it is available, and fall back to the page title (the one
   * specified in the <title> tag of the page).
   *
   * Note that there is a difference between an empty title and a NULL title.
   * An empty string means that somebody specifically set the title to be
   * nothing. NULL means nobody set it. From C++: use IsVoid() and SetIsVoid()
   * to see whether an empty string is "null" or not (it will always be an
   * empty string in either case).
   *
   * @param aUserTitleChanged Is true if the user title was the thing that was
   *                          changed. If false, that means the "real" page
   *                          title was changed instead.
   */
  /* void onTitleChanged (in nsIURI aURI, in AString aPageTitle, in AString aUserTitle, in PRBool aUserTitleChanged); */
  nsresult OnTitleChanged(nsIURI aURI, nsAString * aPageTitle, nsAString * aUserTitle, PRBool aUserTitleChanged);

  /**
   * This page and all of its visits are being deleted. Note: the page may not
   * necessarily have actually existed for this function to be called.
   *
   * Delete notifications are only 99.99% accurate. Batch delete operations
   * must be done in two steps, so first come notifications, then a bulk
   * delete. If there is some error in the middle (for example, out of memory)
   * then you'll get a notification and it won't get deleted. There's no easy
   * way around this.
   */
  /* void onDeleteURI (in nsIURI aURI); */
  nsresult OnDeleteURI(nsIURI aURI);

  /**
   * Notification that all of history is being deleted.
   */
  /* void onClearHistory (); */
  nsresult OnClearHistory();

  /**
   * A page has had some attribute on it changed. Note that for TYPED and
   * HIDDEN, the page may not necessarily have been added yet.
   */
  enum { ATTRIBUTE_FAVICON = 3U };

  /* void onPageChanged (in nsIURI aURI, in PRUint32 aWhat, in AString aValue); */
  nsresult OnPageChanged(nsIURI aURI, PRUint32 aWhat, nsAString * aValue);

  /**
   * Called when a history entry expires. You will recieve notifications that
   * a specific visit has expired with the time of that visit. When the last
   * visit for a history entry expires, the history entry itself is deleted
   * and aWholeEntry is set. (If your observer only cares about URLs and not
   * specific visits, it needs only to listen for aWholeEntry notifications).
   *
   * It is possible for a history entry to be deleted that has no visits if
   * something is out of sync or after a bookmark is deleted that has no
   * visits (thus freeing the history entry). In these cases, aVisitTime will
   * be 0.
   */
  /* void onPageExpired (in nsIURI aURI, in PRTime aVisitTime, in boolean aWholeEntry); */
  nsresult OnPageExpired(nsIURI aURI, PRTime aVisitTime, PRBool aWholeEntry);

}


/* starting interface:    nsINavHistoryQuery */
const char[] NS_INAVHISTORYQUERY_IID_STR = "884819a6-1860-4a71-8fd7-89d962c1d984";

const nsIID NS_INAVHISTORYQUERY_IID= 
  {0x884819a6, 0x1860, 0x4a71, 
    [ 0x8f, 0xd7, 0x89, 0xd9, 0x62, 0xc1, 0xd9, 0x84 ]};

extern(Windows)
interface nsINavHistoryQuery : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYQUERY_IID_STR;
  static const nsIID IID = NS_INAVHISTORYQUERY_IID;

  /**
 * This object encapsulates all the query parameters you're likely to need
 * when building up history UI. All parameters are ANDed together.
 *
 * This is not intended to be a super-general query mechanism. This was designed
 * so that most queries can be done in only one SQL query. This is important
 * because, if the user has their profile on a networked drive, query latency
 * can be non-negligible.
 */
/**
   * Time range for results (INCLUSIVE). The *TimeReference is one of the
   * constants TIME_RELATIVE_* which indicates how to interpret the
   * corresponding time value.
   *   TIME_RELATIVE_EPOCH (default):
   *     The time is relative to Jan 1 1970 GMT, (this is a normal PRTime)
   *   TIME_RELATIVE_TODAY:
   *     The time is relative to this morning at midnight. Normally used for
   *     queries relative to today. For example, a "past week" query would be
   *     today-6 days -> today+1 day
   *   TIME_RELATIVE_NOW:
   *     The time is relative to right now.
   *
   * Note: PRTime is in MICROseconds since 1 Jan 1970. Javascript date objects
   * are expressed in MILLIseconds since 1 Jan 1970.
   *
   * As a special case, a 0 time relative to TIME_RELATIVE_EPOCH indicates that
   * the time is not part of the query. This is the default, so an empty query
   * will match any time. The has* functions return whether the corresponding
   * time is considered.
   *
   * You can read absolute*Time to get the time value that the currently loaded
   * reference points + offset resolve to.
   */
  enum { TIME_RELATIVE_EPOCH = 0U };

  enum { TIME_RELATIVE_TODAY = 1U };

  enum { TIME_RELATIVE_NOW = 2U };

  /* attribute PRTime beginTime; */
  nsresult GetBeginTime(PRTime *aBeginTime);
  nsresult SetBeginTime(PRTime aBeginTime);

  /* attribute PRUint32 beginTimeReference; */
  nsresult GetBeginTimeReference(PRUint32 *aBeginTimeReference);
  nsresult SetBeginTimeReference(PRUint32 aBeginTimeReference);

  /* readonly attribute boolean hasBeginTime; */
  nsresult GetHasBeginTime(PRBool *aHasBeginTime);

  /* readonly attribute PRTime absoluteBeginTime; */
  nsresult GetAbsoluteBeginTime(PRTime *aAbsoluteBeginTime);

  /* attribute PRTime endTime; */
  nsresult GetEndTime(PRTime *aEndTime);
  nsresult SetEndTime(PRTime aEndTime);

  /* attribute PRUint32 endTimeReference; */
  nsresult GetEndTimeReference(PRUint32 *aEndTimeReference);
  nsresult SetEndTimeReference(PRUint32 aEndTimeReference);

  /* readonly attribute boolean hasEndTime; */
  nsresult GetHasEndTime(PRBool *aHasEndTime);

  /* readonly attribute PRTime absoluteEndTime; */
  nsresult GetAbsoluteEndTime(PRTime *aAbsoluteEndTime);

  /**
   * Text search terms.
   */
  /* attribute AString searchTerms; */
  nsresult GetSearchTerms(nsAString * aSearchTerms);
  nsresult SetSearchTerms(nsAString * aSearchTerms);

  /* readonly attribute boolean hasSearchTerms; */
  nsresult GetHasSearchTerms(PRBool *aHasSearchTerms);

  /**
   * When set, returns only bookmarked items, when unset, returns anything. Setting this
   * is equivalent to listing all bookmark folders in the 'folders' parameter.
   */
  /* attribute boolean onlyBookmarked; */
  nsresult GetOnlyBookmarked(PRBool *aOnlyBookmarked);
  nsresult SetOnlyBookmarked(PRBool aOnlyBookmarked);

  /**
   * This controls the meaning of 'domain', and whether it is an exact match
   * 'domainIsHost' = true, or hierarchical (= false).
   */
  /* attribute boolean domainIsHost; */
  nsresult GetDomainIsHost(PRBool *aDomainIsHost);
  nsresult SetDomainIsHost(PRBool aDomainIsHost);

  /**
   * This is the host or domain name (controlled by domainIsHost). When
   * domainIsHost, domain only does exact matching on host names. Otherwise,
   * it will return anything whose host name ends in 'domain'.
   *
   * This one is a little different than most. Setting it to an empty string
   * is a real query and will match any URI that has no host name (local files
   * and such). Set this to NULL (in C++ use SetIsVoid) if you don't want
   * domain matching.
   */
  /* attribute AUTF8String domain; */
  nsresult GetDomain(nsACString * aDomain);
  nsresult SetDomain(nsACString * aDomain);

  /* readonly attribute boolean hasDomain; */
  nsresult GetHasDomain(PRBool *aHasDomain);

  /**
   * Controls the interpretation of 'uri'. When unset (default), the URI will
   * request an exact match of the specified URI. When set, any history entry
   * beginning in 'uri' will match. For example "http://bar.com/foo" will match
   * "http://bar.com/foo" as well as "http://bar.com/foo/baz.gif".
   */
  /* attribute boolean uriIsPrefix; */
  nsresult GetUriIsPrefix(PRBool *aUriIsPrefix);
  nsresult SetUriIsPrefix(PRBool aUriIsPrefix);

  /**
   * This is a URI to match, to, for example, find out every time you visited
   * a given URI. Use uriIsPrefix to control whether this is an exact match.
   */
  /* attribute nsIURI uri; */
  nsresult GetUri(nsIURI  *aUri);
  nsresult SetUri(nsIURI  aUri);

  /* readonly attribute boolean hasUri; */
  nsresult GetHasUri(PRBool *aHasUri);

  /**
   * Test for existance or non-existance of a given annotation. We don't
   * currently support >1 annotation name per query. If 'annotationIsNot' is
   * true, we test for the non-existance of the specified annotation.
   *
   * Testing for not annotation will do the same thing as a normal query and
   * remove everything that doesn't have that annotation. Asking for things
   * that DO have a given annotation is a little different. It also includes
   * things that have never been visited. This allows place queries to be
   * returned (which might include bookmark folders -- use the bookmark
   * service's GetFolderURI) as well as anything else that may have been
   * tagged with an annotation. This will only work for RESULTS_AS_URI since
   * there will be no visits for these items.
   */
  /* attribute boolean annotationIsNot; */
  nsresult GetAnnotationIsNot(PRBool *aAnnotationIsNot);
  nsresult SetAnnotationIsNot(PRBool aAnnotationIsNot);

  /* attribute AUTF8String annotation; */
  nsresult GetAnnotation(nsACString * aAnnotation);
  nsresult SetAnnotation(nsACString * aAnnotation);

  /* readonly attribute boolean hasAnnotation; */
  nsresult GetHasAnnotation(PRBool *aHasAnnotation);

  /**
   * Limit results to items that are in all of the given folders.
   */
  /* void getFolders (out PRUint32 count, [array, size_is (count), retval] out PRInt64 folders); */
  nsresult GetFolders(PRUint32 *count, PRInt64 **folders);

  /* readonly attribute PRUint32 folderCount; */
  nsresult GetFolderCount(PRUint32 *aFolderCount);

  /* void setFolders ([array, size_is (folderCount), const] in PRInt64 folders, in PRUint32 folderCount); */
  nsresult SetFolders(PRInt64 *folders, PRUint32 folderCount);

  /**
   * Creates a new query item with the same parameters of this one.
   */
  /* nsINavHistoryQuery clone (); */
  nsresult Clone(nsINavHistoryQuery *_retval);

}


/* starting interface:    nsINavHistoryQueryOptions */
const char[] NS_INAVHISTORYQUERYOPTIONS_IID_STR = "25fd4de4-33b0-475e-a63d-2bcb1d123e0d";

const nsIID NS_INAVHISTORYQUERYOPTIONS_IID= 
  {0x25fd4de4, 0x33b0, 0x475e, 
    [ 0xa6, 0x3d, 0x2b, 0xcb, 0x1d, 0x12, 0x3e, 0x0d ]};

extern(Windows)
interface nsINavHistoryQueryOptions : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYQUERYOPTIONS_IID_STR;
  static const nsIID IID = NS_INAVHISTORYQUERYOPTIONS_IID;

  /**
 * This object represents the global options for executing a query.
 */
/**
   * Groping by exact host. The results will be an array of nsINavHistoryResults
   * with type = RESULT_TYPE_HOST, one for each unique host (for example,
   * "bugzilla.mozilla.org" and "www.mozilla.org" will be separate). The
   * children of these will correspond to the results for each host.
   */
  enum { GROUP_BY_HOST = 1U };

  /**
   * Grouping by toplevel domain. Similar to GROUP_BY_HOST, but there will be
   * one result for each toplevel domain (mozilla.org will be one entry, and
   * will contain results including, for example, "bugzilla.mozilla.org" and
   * "www.mozilla.org").
   */
  enum { GROUP_BY_DOMAIN = 2U };

  /**
   * Group by bookmark folder.  Since this determines the entire subtree
   * hierarchy, it must be the last grouping option given.  This option
   * requires the query to have onlyBookmarked set, and for there to be
   * at least one parent folder specified via nsINavHistoryQuery::setFolders.
   * If all of the top-level results belong to a single folder, the folder will
   * be omitted and its children will become the toplevel result nodes.
   */
  enum { GROUP_BY_FOLDER = 3U };

  /**
   * You can ask for the results to be pre-sorted. Since the DB has indices
   * of many items, it can produce sorted results almost for free. These should
   * be self-explanatory.
   *
   * Note: re-sorting is slower, as is sorting by title or when you have a
   * host name.
   *
   * For bookmark items, SORT_BY_NONE means sort by the natural bookmark order.
   */
  enum { SORT_BY_NONE = 0U };

  enum { SORT_BY_TITLE_ASCENDING = 1U };

  enum { SORT_BY_TITLE_DESCENDING = 2U };

  enum { SORT_BY_DATE_ASCENDING = 3U };

  enum { SORT_BY_DATE_DESCENDING = 4U };

  enum { SORT_BY_URI_ASCENDING = 5U };

  enum { SORT_BY_URI_DESCENDING = 6U };

  enum { SORT_BY_VISITCOUNT_ASCENDING = 7U };

  enum { SORT_BY_VISITCOUNT_DESCENDING = 8U };

  /**
   * "URI" results, one for each URI visited in the range. Individual result
   * nodes will be of type "URI".
   */
  enum { RESULTS_AS_URI = 0U };

  /**
   * "Visit" results, with one for each time a page was visited (this will
   * often give you multiple results for one URI). Individual result nodes will
   * have type "Visit"
   */
  enum { RESULTS_AS_VISIT = 1U };

  /**
   * This is identical to RESULT_TYPE_VISIT except that individual result nodes
   * will have type "FullVisit".  This is used for the attributes that are not
   * commonly accessed to save space in the common case (the lists can be very
   * long).
   */
  enum { RESULTS_AS_FULL_VISIT = 2U };

  /**
   * The grouping mode to be used for this query.
   * Grouping mode is an array of GROUP_BY_* values that specifies the
   * structure of the tree you want. If you don't want grouping, you can
   * specify an empty array.
   */
  /* void getGroupingMode (out PRUint32 groupCount, [array, size_is (groupCount), retval] out PRUint32 groupingMode); */
  nsresult GetGroupingMode(PRUint32 *groupCount, PRUint32 **groupingMode);

  /* void setGroupingMode ([array, size_is (groupCount), const] in PRUint32 groupingMode, in PRUint32 groupCount); */
  nsresult SetGroupingMode(PRUint32 *groupingMode, PRUint32 groupCount);

  /**
   * The sorting mode to be used for this query.
   * mode is one of SORT_BY_*
   */
  /* attribute PRUint32 sortingMode; */
  nsresult GetSortingMode(PRUint32 *aSortingMode);
  nsresult SetSortingMode(PRUint32 aSortingMode);

  /**
   * Sets the result type. One of RESULT_TYPE_* which includes how URIs are
   * represented.
   */
  /* attribute PRUint32 resultType; */
  nsresult GetResultType(PRUint32 *aResultType);
  nsresult SetResultType(PRUint32 aResultType);

  /**
   * This option excludes all URIs and separators from a bookmarks query.
   * This would be used if you just wanted a list of bookmark folders and
   * queries (such as the left pane of the places page).
   * Ignored for queries over history. Defaults to false.
   */
  /* attribute boolean excludeItems; */
  nsresult GetExcludeItems(PRBool *aExcludeItems);
  nsresult SetExcludeItems(PRBool aExcludeItems);

  /**
   * Set to true to exclude queries ("place:" URIs) from the query results.
   * Simple folder queries (bookmark folder symlinks) will still be included.
   * Defaults to false.
   */
  /* attribute boolean excludeQueries; */
  nsresult GetExcludeQueries(PRBool *aExcludeQueries);
  nsresult SetExcludeQueries(PRBool aExcludeQueries);

  /**
   * Set to true to exclude read-only folders from the query results. This is
   * designed for cases where you want to give the user the option of filing
   * something into a list of folders. It only affects cases where the actual
   * folder result node would appear in its parent folder and filters it out.
   * It doesn't affect the query at all, and doesn't affect more complex
   * queries (such as "folders with annotation X").
   */
  /* attribute boolean excludeReadOnlyFolders; */
  nsresult GetExcludeReadOnlyFolders(PRBool *aExcludeReadOnlyFolders);
  nsresult SetExcludeReadOnlyFolders(PRBool aExcludeReadOnlyFolders);

  /**
   * When set, allows items with "place:" URIs to appear as containers,
   * with the container's contents filled in from the stored query.
   * If not set, these will appear as normal items. Doesn't do anything if
   * excludeQueries is set. Defaults to false.
   *
   * Note that this has no effect on folder links, which are place: URIs
   * returned by nsINavBookmarkService.GetFolderURI. These are always expanded
   * and will appear as bookmark folders.
   */
  /* attribute boolean expandQueries; */
  nsresult GetExpandQueries(PRBool *aExpandQueries);
  nsresult SetExpandQueries(PRBool aExpandQueries);

  /**
   * Normally the title of a result will be the user's custom title if there is
   * one, falling back on the default page title. If this is set, we will not
   * do this operation and always use the original page title extracted from
   * the HTML of the page. Defaults to false.
   */
  /* attribute boolean forceOriginalTitle; */
  nsresult GetForceOriginalTitle(PRBool *aForceOriginalTitle);
  nsresult SetForceOriginalTitle(PRBool aForceOriginalTitle);

  /**
   * Most items in history are marked "hidden." Only toplevel pages that the
   * user sees in the URL bar are not hidden. Hidden things include the content
   * of iframes and all images on web pages. Normally, you don't want these
   * things. If you do, set this flag and you'll get all items, even hidden
   * ones. Does nothing for bookmark queries. Defaults to false.
   */
  /* attribute boolean includeHidden; */
  nsresult GetIncludeHidden(PRBool *aIncludeHidden);
  nsresult SetIncludeHidden(PRBool aIncludeHidden);

  /**
   * This is the maximum number of results that you want. The query is exeucted,
   * the results are sorted, and then the top 'maxResults' results are taken
   * and returned. Set to 0 (the default) to get all results.
   *
   * THIS DOES NOT WORK IN CONJUNCTION WITH SORTING BY TITLE. This is because
   * sorting by title requires us to sort after using locale-sensetive sorting
   * (as opposed to letting the database do it for us).
   *
   * Instead, we get the result ordered by date, pick the maxResult most recent
   * ones, and THEN sort by title.
   */
  /* attribute PRUint32 maxResults; */
  nsresult GetMaxResults(PRUint32 *aMaxResults);
  nsresult SetMaxResults(PRUint32 aMaxResults);

  /**
   * Creates a new options item with the same parameters of this one.
   */
  /* nsINavHistoryQueryOptions clone (); */
  nsresult Clone(nsINavHistoryQueryOptions *_retval);

}


/* starting interface:    nsINavHistoryService */
const char[] NS_INAVHISTORYSERVICE_IID_STR = "c51f54cb-5e89-4b20-a37c-1343888935b7";

const nsIID NS_INAVHISTORYSERVICE_IID= 
  {0xc51f54cb, 0x5e89, 0x4b20, 
    [ 0xa3, 0x7c, 0x13, 0x43, 0x88, 0x89, 0x35, 0xb7 ]};

extern(Windows)
interface nsINavHistoryService : nsISupports {
  static const char[] IID_STR = NS_INAVHISTORYSERVICE_IID_STR;
  static const nsIID IID = NS_INAVHISTORYSERVICE_IID;

  /**
   * This transition type means the user followed a link and got a new toplevel
   * window.
   */
  enum { TRANSITION_LINK = 1U };

  /**
   * This transition type means that the user typed the page's URL in the
   * URL bar.
   */
  enum { TRANSITION_TYPED = 2U };

  /**
   * This transition is set when the user followed a bookmark to get to the
   * page.
   */
  enum { TRANSITION_BOOKMARK = 3U };

  /**
   * This transition type is set when some inner content is loaded. This is
   * true of all images on a page, and the contents of the iframe. It is also
   * true of any content in a frame, regardless if whether or not the user
   * clicked something to get there.
   */
  enum { TRANSITION_EMBED = 4U };

  /**
   * Set when the transition was a permanent redirect.
   */
  enum { TRANSITION_REDIRECT_PERMANENT = 5U };

  /**
   * Set when the transition was a temporary redirect.
   */
  enum { TRANSITION_REDIRECT_TEMPORARY = 6U };

  /**
   * True if there is any history. This can be used in UI to determine whether
   * the "clear history" button should be enabled or not. This is much better
   * than using BrowserHistory.count since that can be very slow if there is
   * a lot of history (it must enumerate each item). This is pretty fast.
   */
  /* readonly attribute boolean hasHistoryEntries; */
  nsresult GetHasHistoryEntries(PRBool *aHasHistoryEntries);

  /**
   * This sets the user-defined title of the page. Silently fails if we have
   * no knowledge of this page. Set to empty string to clear the user title and
   * only use the "real" title as declared on the page.
   */
  /* void setPageUserTitle (in nsIURI aURI, in AString aUserTitle); */
  nsresult SetPageUserTitle(nsIURI aURI, nsAString * aUserTitle);

  /**
   * This is just like markPageAsTyped (in nsIBrowserHistory, also implemented
   * by the history service), but for bookmarks. It declares that the given URI
   * is being opened as a result of following a bookmark. If this URI is loaded
   * soon after this message has been received, that transition will be marked
   * as following a bookmark.
   */
  /* void markPageAsFollowedBookmark (in nsIURI aURI); */
  nsresult MarkPageAsFollowedBookmark(nsIURI aURI);

  /**
   * Returns true if this URI would be added to the history. You don't have to
   * worry about calling this, addPageToSession/addURI will always check before
   * actually adding the page. This function is public because some components
   * may want to check if this page would go in the history (i.e. for
   * annotations).
   */
  /* boolean canAddURI (in nsIURI aURI); */
  nsresult CanAddURI(nsIURI aURI, PRBool *_retval);

  /**
   * Call to set the full information for a given page. If the page does not
   * exist, it will be added to the database. If it does, the existing values
   * WILL BE OVERWRITTEN. This is an updated version of addPageWithDetails
   * for backup/restore type operations.
   *
   * @param aURI        Page to add/change.
   * @param aTitle      Title as specified by the page.
   * @param aUserTitle  Custom title provided by user. Set to NULL if none.
   * @param aVisitCount Number of times this page has been visited. Setting this
   *                    to 0 may make the page invisible in some views.
   * @param aHidden     Whether the page is hidden. If the page has only
   *                    TRANSITION_EMBED visits, this will be true, otherwise
   *                    false.
   * @param aTyped      True if this URI has ever been typed.
   */
  /* void setPageDetails (in nsIURI aURI, in AString aTitle, in AString aUserTitle, in PRUint32 aVisitCount, in boolean aHidden, in boolean aTyped); */
  nsresult SetPageDetails(nsIURI aURI, nsAString * aTitle, nsAString * aUserTitle, PRUint32 aVisitCount, PRBool aHidden, PRBool aTyped);

  /**
   * Call to manually add a visit for a specific page. This will probably not
   * be commonly used other than for backup/restore type operations. If the URI
   * does not have an entry in the history database already, one will be created
   * with no visits, no title, hidden, not typed.  Adding a visit will
   * automatically increment the visit count for the visited page and will unhide
   * it and/or mark it typed according to the transition type.
   *
   * @param aURI             Visited page
   * @param aTime            Time page was visited (microseconds)
   * @param aReferringVisit  The ID of the visit that generated this one. Use 0
   *                         for no referrer. This must be a valid visit already
   *                         in the DB or 0.
   * @param aTranstitionType Type of transition: one of TRANSITION_* above
   * @param aIsRedirect      True if the given visit redirects to somewhere else.
   *                         (ie you will create an visit out of here that is a
   *                         redirect transition). This causes this page to be
   *                         hidden in normal history views (unless it has been
   *                         unhidden by visiting it with a non-redirect).
   * @param aSessionID       The session ID that this page belongs to. Use 0 for
   *                         no session.
   * @returns The ID of the created visit. This will be 0 if the URI is not
   *          valid for adding to history (canAddURI = false).
   */
  /* PRInt64 addVisit (in nsIURI aURI, in PRTime aTime, in PRInt64 aReferringVisit, in PRInt32 aTransitionType, in boolean aIsRedirect, in PRInt64 aSessionID); */
  nsresult AddVisit(nsIURI aURI, PRTime aTime, PRInt64 aReferringVisit, PRInt32 aTransitionType, PRBool aIsRedirect, PRInt64 aSessionID, PRInt64 *_retval);

  /**
   * This returns a new query object that you can pass to executeQuer[y/ies].
   * It will be initialized to all empty (so using it will give you all history).
   */
  /* nsINavHistoryQuery getNewQuery (); */
  nsresult GetNewQuery(nsINavHistoryQuery *_retval);

  /**
   * This returns a new options object that you can pass to executeQuer[y/ies]
   * after setting the desired options.
   */
  /* nsINavHistoryQueryOptions getNewQueryOptions (); */
  nsresult GetNewQueryOptions(nsINavHistoryQueryOptions *_retval);

  /**
   * Executes a single query.
   */
  /* nsINavHistoryResult executeQuery (in nsINavHistoryQuery aQuery, in nsINavHistoryQueryOptions options); */
  nsresult ExecuteQuery(nsINavHistoryQuery aQuery, nsINavHistoryQueryOptions options, nsINavHistoryResult *_retval);

  /**
   * Executes an array of queries. All of the query objects are ORed
   * together. Within a query, all the terms are ANDed together as in
   * executeQuery. See executeQuery()
   */
  /* nsINavHistoryResult executeQueries ([array, size_is (aQueryCount)] in nsINavHistoryQuery aQueries, in PRUint32 aQueryCount, in nsINavHistoryQueryOptions options); */
  nsresult ExecuteQueries(nsINavHistoryQuery *aQueries, PRUint32 aQueryCount, nsINavHistoryQueryOptions options, nsINavHistoryResult *_retval);

  /**
   * Converts a query URI-like string to an array of actual query objects for
   * use to executeQueries(). The output query array may be empty if there is
   * no information. However, there will always be an options structure returned
   * (if nothing is defined, it will just have the default values).
   */
  /* void queryStringToQueries (in AUTF8String aQueryString, [array, size_is (aResultCount)] out nsINavHistoryQuery aQueries, out PRUint32 aResultCount, out nsINavHistoryQueryOptions options); */
  nsresult QueryStringToQueries(nsACString * aQueryString, nsINavHistoryQuery **aQueries, PRUint32 *aResultCount, nsINavHistoryQueryOptions *options);

  /**
   * Converts a query into an equivalent string that can be persisted. Inverse
   * of queryStringToQueries()
   */
  /* AUTF8String queriesToQueryString ([array, size_is (aQueryCount)] in nsINavHistoryQuery aQueries, in PRUint32 aQueryCount, in nsINavHistoryQueryOptions options); */
  nsresult QueriesToQueryString(nsINavHistoryQuery *aQueries, PRUint32 aQueryCount, nsINavHistoryQueryOptions options, nsACString * _retval);

  /**
   * Adds a history observer. If ownsWeak is false, the history service will
   * keep an owning reference to the observer.  If ownsWeak is true, then
   * aObserver must implement nsISupportsWeakReference, and the history service
   * will keep a weak reference to the observer.
   */
  /* void addObserver (in nsINavHistoryObserver observer, in boolean ownsWeak); */
  nsresult AddObserver(nsINavHistoryObserver observer, PRBool ownsWeak);

  /**
   * Removes a history observer.
   */
  /* void removeObserver (in nsINavHistoryObserver observer); */
  nsresult RemoveObserver(nsINavHistoryObserver observer);

  /**
   * Causes observers to be notified of a beginUpdateBatch when a lot of things
   * are about to change. Calls can be nested, observers will only be
   * notified when all batches begin/end.
   */
  /* void beginUpdateBatch (); */
  nsresult BeginUpdateBatch();

  /**
   * Causes observers to be notified of an endUpdateBatch when a batch is
   * done changing. Should match beginUpdateBatch or bad things will happen.
   */
  /* void endUpdateBatch (); */
  nsresult EndUpdateBatch();

}


/* starting interface:    nsIMorkHistoryImporter */
const char[] NS_IMORKHISTORYIMPORTER_IID_STR = "be935aed-6929-4e44-be29-17ec89e5c8bd";

const nsIID NS_IMORKHISTORYIMPORTER_IID= 
  {0xbe935aed, 0x6929, 0x4e44, 
    [ 0xbe, 0x29, 0x17, 0xec, 0x89, 0xe5, 0xc8, 0xbd ]};

/**
 * nsIMorkHistoryImporter is a service which handles importing old
 * history files.
 */
extern(Windows)
interface nsIMorkHistoryImporter : nsISupports {
  static const char[] IID_STR = NS_IMORKHISTORYIMPORTER_IID_STR;
  static const nsIID IID = NS_IMORKHISTORYIMPORTER_IID;

  /**
   * Import the given Mork history file.
   *  @param file     The Mork history file to import
   *  @param history  A reference to the nsINavHistoryService.  This is
   *                  supplied since the importer is invoked during
   *                  history service initialization.
   */
  /* void importHistory (in nsIFile file, in nsINavHistoryService history); */
  nsresult ImportHistory(nsIFile file, nsINavHistoryService history);

}

